-- SOCCER_SQL_021
-- 이현 선수 소속팀의 선수명단 출력
SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
FROM PLAYER
WHERE TEAM_ID LIKE (SELECT TEAM_ID
                    FROM PLAYER
                    WHERE PLAYER_NAME LIKE '이현')
ORDER BY PLAYER_NAME;

-- SOCCER_SQL_022
-- NULL 처리에 있어
-- SUM(NVL(SAL,0)) 로 하지말고
-- NVL(SUM(SAL),0) 으로 해야 자원낭비가 줄어든다
 -- 팀별 포지션별 인원수와 팀별 전체 인원수 출력
 -- Oracle, Simple Case Expr 
SELECT TEAM_ID, 
COUNT(CASE WHEN POSITION LIKE 'FW' THEN 1 END) "FW",
COUNT(CASE WHEN POSITION LIKE 'MF' THEN 1 END) "MF",
COUNT(CASE WHEN POSITION LIKE 'DF' THEN 1 END) "DF",
COUNT(CASE WHEN POSITION LIKE 'GK' THEN 1 END) "GK",
COUNT(*) "SUM"
FROM PLAYER
GROUP BY TEAM_ID; -- NULL값이 포함 안됌 K08

-- SOCCER_SQL_023
-- GROUP BY 절 없이 전체 선수들의 포지션별 평균 키 및 전체 평균 키 출력
SELECT
    ROUND(AVG(CASE WHEN POSITION LIKE 'MF' THEN HEIGHT END),2) "미드필더",
    ROUND(AVG(CASE WHEN POSITION LIKE 'FW' THEN HEIGHT END),2) "포워드",
    ROUND(AVG(CASE WHEN POSITION LIKE 'DF' THEN HEIGHT END),2) "디펜더",
    ROUND(AVG(CASE WHEN POSITION LIKE 'GK' THEN HEIGHT END),2) "골키퍼",
    ROUND(AVG(HEIGHT),2) "전체평균 키"
FROM PLAYER;

-- SOCCER_SQL_024 
-- 소속팀별 키가 가장 작은 사람들의 정보
SELECT P.TEAM_ID 팀아이디, TEAM_NAME 팀명, PLAYER_NAME 선수, 
        POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER P
    JOIN TEAM T
        ON P.TEAM_ID LIKE T.TEAM_ID
WHERE P.HEIGHT LIKE (SELECT MIN(HEIGHT)
                     FROM PLAYER
                     WHERE HEIGHT
                     GROUP BY TEAM_ID);